#!/usr/bin/env python3
"""
Author:
    Dr. Ceasar Jackson Jr.

Purpose:
    Synchronize readiness calculations and reports.

Validation:
    python -m py_compile tools/sync_readiness.py
    python -m pytest tests/test_sync_readiness.py -v
"""


def calculate_readiness(manifest: dict) -> int:
    """
    Calculate readiness score based on the manifest data.
    """
    # Preferred: current manifest schema generated by generate_report.py
    if "packages_pass" in manifest:
        pass_count = int(manifest.get("packages_pass", 0))
        fail_count = int(manifest.get("packages_fail", 0))
        incompat_count = int(manifest.get("packages_incompat", 0))
        blocked_count = int(manifest.get("packages_blocked", 0))
        skip_count = int(manifest.get("packages_skip", 0))

        # Older manifests may omit packages_blocked.
        # Reconstruct it from results if available.
        if blocked_count == 0:
            results = manifest.get("results", {})
            blocked_count = sum(
                1
                for details in results.values()
                if str(details.get("status", "")).upper() == "BLOCKED"
            )

    else:
        results = manifest.get("validation_results") or manifest.get("results") or {}

        if results:
            pass_count = 0
            fail_count = 0
            incompat_count = 0
            blocked_count = 0
            skip_count = 0

            for details in results.values():
                status = str(details.get("status", "")).upper()

                if status == "PASS":
                    pass_count += 1
                elif status == "FAIL":
                    fail_count += 1
                elif status == "INCOMPAT":
                    incompat_count += 1
                elif status == "BLOCKED":
                    blocked_count += 1
                elif status == "SKIP":
                    skip_count += 1
        else:
            pass_count = int(manifest.get("pass", 0))
            fail_count = int(manifest.get("fail", 0))
            incompat_count = int(manifest.get("incompat", 0))
            blocked_count = int(manifest.get("blocked", 0))
            skip_count = int(manifest.get("skip", 0))

    total = pass_count + fail_count + incompat_count + blocked_count + skip_count
    if total == 0:
        return 0
    readiness = (pass_count / total) * 100
    return int(readiness)
